### ISSUE TITLE
iobroker-react cannot connect to the socket as of v1.1.1

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/socket-client#16]
Hello @GermanBluefox,
I upgraded iobroker-react from AlCalzone to the new adapter-react-v5 and mui v5 and in the same move I wanted to update all dependencies.
When I upgraded the socket-client to v1.1.14, the adapter UI did not connect anymore, only this message appears in the console.
![image](https://user-images.githubusercontent.com/32600934/198845543-2ae14003-18d1-4967-a955-834eaa35a5d7.png)
Then I tried the different versions and this problem occurs from version 1.1.1.
I currently have the socket-client on the v1.0.12 in the repo, could you take a look at what this can be?
Here is the [link](https://github.com/xXBJXx/iobroker-react) to the repo

**Comment by GermanBluefox** [comment]
Please try with new version

**Comment by xXBJXx** [comment]
Tried it with the latest version 2.0.4, still the same problem 
![image](https://user-images.githubusercontent.com/32600934/219375338-2cdad524-c9ec-49c6-a47b-3d351bd76b70.png)
iobroker-react test repo => [branch testNewSocketVersion](https://github.com/xXBJXx/iobroker-react/tree/testNewSocketVersion)
test adapter with iobroker-react installed => [test Adapter](https://github.com/xXBJXx/ioBroker.template_react/tree/newSocketVersion)

**Comment by AlCalzone** [comment]
@xXBJXx Firefox or chrome?

**Comment by xXBJXx** [comment]
chrome

**Comment by AlCalzone** [comment]
I think this is related to `dev-server`. Left "official" port, right "internal" port:

![grafik](https://user-images.githubusercontent.com/17641229/219478139-3aead13e-d81e-4f76-9775-0fe4ea028b1a.png)

**Comment by AlCalzone** [comment]
> v1.1.1 added the pathname to the websocket URL: [c8efda6](https://github.com/ioBroker/socket-client/commit/c8efda6c3948a82f07f0173f95d52c0afbd9a33f)
> 
> maybe that's the reason?

That is the reason. If I change this, dev-server works again:
```diff
		const url = port
-			? `${protocol}://${host}:${port}${path}`
-			: `${protocol}://${host}${path}`;
+			? `${protocol}://${host}:${port}`
+			: `${protocol}://${host}`;

		this._socket = window.io.connect(url, {
			path: path.endsWith("/") ? `${path}socket.io` : `${path}/socket.io`,
			query: "ws=true",
			name: this.props.name,
			timeout: this.props.ioTimeout,
			uuid: this.props.uuid,
			token: this.props.token,
		});
```

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/socket-client/commit/959eec0eab3adaa7deee66b6c92298ad2770921f
