### ISSUE TITLE
auto completion and type detection not working in commonJS environments?

### ISSUE THREAD

**Issue by stevenengland** [ioBroker/socket-client#21]
Hi together,

I am using a template created by `create-adapter` that is more geared towards commonJS. In my `.ts` and `.tsx` files for the admin part of the adapter, if I want to reference the socket object (which is a `ConnectionClass`/`Connection` introduced via `adapter-react-v5` -> `socket-client`) I do not have auto completion support nor type annotations at hand. As far as I can read the build script (especially [here](https://github.com/ioBroker/socket-client/blob/72dc1abefe053638723f462f08f092f16a2e5e05/package.json#L15)) for this repo here I would say it shall work for commonJS as well as ESM, should'nt it? 

![image](https://github.com/ioBroker/socket-client/assets/11787949/f9fbee6b-e7c9-40f5-b797-949b310b5001)

**Comment by Apollon77** [comment]
how your tsconfig looks like from your project?
especially what is set in moduleResolution? try setting "Node16" there if not

**Comment by stevenengland** [comment]
Hi @Apollon77 , at least for the socket object of the `GenericApp` class I now know what the problem is. Compared to a reaaaally fresh adapter mine now uses `adapter-react-v5`. Problem:
`adapter-react` exposes the `socket` as `Connection`:
![image](https://github.com/ioBroker/socket-client/assets/11787949/7bbd6292-0e4e-41c7-80ad-155a24f6b7e2)
`adapter-react-v5` does not:
![image](https://github.com/ioBroker/socket-client/assets/11787949/41f6b968-0dd7-434d-b6dc-8a1847ffd67b)

So it is no wonder that in a v5 adapter I can't have autocompletion. I will now have a look, why I have further problems if I want to use the `Connection` class itself:
![image](https://github.com/ioBroker/socket-client/assets/11787949/51670169-045e-4035-ac02-501e7fce7a30)

Do you think there was a good reason to switch to any instead of a concrete class? Shall I open an issue against v5?

**Comment by Apollon77** [comment]
@AlCalzone @foxriver76 An idea/insights?
