### ISSUE TITLE
subscribeObject not working anymore (2.4.x)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/socket-client#23]
Maybe related to 5d7f0f4fc5207e6018c1fd9f84c6bb9ccaf62a23

ioBroker.javascript uses `this.socket.subscribeObject('script.*', this.onScriptsChanged);` to subscribe to all scripts. Looks like this is **not working with the latest version 2.4.3** (or `>=2.4.0`)

Reported here https://forum.iobroker.net/topic/73946/javascript-adapter-8-0-0

```
mkleine@iobroker-dev:~/ioBroker.javascript/src$ npm ls @iobroker/socket-client
js@8.0.0 /home/mkleine/ioBroker.javascript/src
└─┬ @iobroker/adapter-react-v5@4.13.5
  └── @iobroker/socket-client@2.4.3
```

----

### Older version is working

Added an override (and package `"@iobroker/adapter-react-v5": "~4.10.4"` to `src` solves the problem:

```
    "overrides": {
        "@iobroker/adapter-react-v5": {
          "@iobroker/socket-client": "~2.3.16"
        }
    },
```

```
mkleine@iobroker-dev:~/ioBroker.javascript/src$ npm ls @iobroker/socket-client
js@8.0.0 /home/mkleine/ioBroker.javascript/src
└─┬ @iobroker/adapter-react-v5@4.10.4 overridden
  └── @iobroker/socket-client@2.3.16 overridden
```

**Comment by klein0r** [comment]
`toSubscribe` has always a length of 0 (never filled)

https://github.com/ioBroker/socket-client/blob/5d7f0f4fc5207e6018c1fd9f84c6bb9ccaf62a23/src/Connection.ts#L802-L818

**Comment by klein0r** [comment]
Looks like @iobroker/adapter-react-v5 `src/LegacyConnection.js` had the same problem some month ago:

https://github.com/ioBroker/adapter-react-v5/commit/22454112efadc1a8d21427aa34afabb30926b053

**Comment by GermanBluefox** [comment]
@klein0r Thank you for investigation
