### ISSUE TITLE
Typescript warnings

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/socket-client#3]
@jogibear9988 I am not able to fix these warnings: https://github.com/ioBroker/socket-client/runs/2792473907?check_suite_focus=true#step:5:14
Can you fix it?

**Comment by jogibear9988** [comment]
Hopefully my Pull Request fixes them. 
Think the "dev" dependencies are not installed when running deploy? But we will see

**Comment by jogibear9988** [comment]
@GermanBluefox  should now work

**Comment by GermanBluefox** [comment]
Perfect. Thank you
