### ISSUE TITLE
Unable to use it in react with create-react-app

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/socket-client#6]
![image](https://user-images.githubusercontent.com/4582016/125326317-3450f680-e342-11eb-95a7-531d0be0c0a5.png)

How to add custom plugin to create-react-app ?

**Comment by GermanBluefox** [comment]
Thank you @AlCalzone !
I could build admin with socket-client.

**Comment by AlCalzone** [comment]
:)

**Comment by GermanBluefox** [comment]
Damn. Still cannot build :(

**Comment by AlCalzone** [comment]
What's the issue?

**Comment by GermanBluefox** [comment]
> What's the issue?

Missing "@babel/plugin-proposal-class-properties". Now it is OK.

**Comment by AlCalzone** [comment]
Hmm, we should probably change the compilation target to something that doesn't require further transpilation.

**Comment by GermanBluefox** [comment]
Yes. That should be nice, as it will be used not only in admin, but everywhere.

**Comment by AlCalzone** [comment]
I checked yesterday in the npm package and it already is. The classes in compiled JS files have class methods, but no class properties which your error message suggests. I guess I need to see a repro to figure out what's happening.
